angular.module('trainee', ['controllers', 'services']);

angular.module('services', [])
  .factory('Questions', ['$http', function ($http) {
    return {
      name: 'Question Service',
      get: function (callback) {
        // $http.get('http://example.com').success(function (data) {
        //   callback(data);
        // });
        callback(questions);
      }
    };
  }]);

angular.module('controllers', [])
  .controller('TraineeCtrl', ['$scope', 'Questions', function ($scope, Questions) {

    Questions.get(function (questions) {
      $scope.questions = questions;
    });


  $(function(){$("input").on("click", function (event) {
    var $this = $(this);
    var question_string = $this.parent().children().first().text();

    var find = function (list, key, value) {
      for (var i = 0; i < list.length; i++) {
        if (list[i][key] === value) {
          return list[i];
        }
      }
    };


    var qo = find($scope.questions, "question", question_string);
    var attempt = $this.val();

    console.log(qo);
    console.log(attempt);

    if (qo["answer"][0] === attempt.slice(0,1)) {
      alert("WOW");
    }

  });});

  }]);

var questions = [{
    "id": 0,
    "question": "1. You are attempting to add new keywords to a SharePoint and receive a message that \r\nstates The Site Does Not Contain A Default Keywords Store. How should you correct \r\nthis issue?",
    "answer": ["C"],
    "a": "A. Add an enterprise keywords site column to the site’s content types.\r\n",
    "b": "B. In Central Administration, add an MMS application to the SharePoint farm.\r\n",
    "c": "C. Edit the MMS Connection and then select This Service Application Is The Default \r\nStorage Location For Keywords.\r\n",
    "d": "D. Activate the managed keyword service application in Central Administration.\r\n\r",
    "a_answer": " Incorrect: An enterprise keywords site column is used for keyword storage, but \r\nwill not cause the error.",
    "b_answer": " Incorrect: Although the MMS is indeed required, additional configuration steps \r\nare required.\r",
    "c_answer": " Correct: A default keywords term store must be selected in the MMS for enterprise \r\nkeywords to be used.\r\nD.",
    "d_answer": " Incorrect: No Managed Keyword Service application exists in SharePoint 2013.\r\n\r\n"
}, {
    "id": 0,
    "question": "2. You want to define a new information policy feature. The legal requirement for the \r\ndocument type requires that you produce and retain physical copies of each document. \r\nYou want to use a policy feature that will be supported in the next version of \r\nSharePoint.\r\n\r\n\r\nWhich of the following policy feature types should you choose?",
    "answer": ["B"],
    "a": "A. Retention\r\n",
    "b": "B. Bar codes\r\n",
    "c": "C. Labels\r\n",
    "d": "D. Auditing\r\n\r",
    "a_answer": " Incorrect: The retention policy feature defines the lifecycle of content contained \r\nwithin SharePoint.",
    "b_answer": " Correct: The barcode policy feature is the only feature type that is both supported \r\nbeyond SharePoint 2013 and useful for tracking physical documents.\r",
    "c_answer": " Incorrect: The labeling policy feature is a backward-compatible feature that works \r\nwith printed documents; it is also deprecated, meaning that it will not be available \r\nin newer versions of SharePoint (beyond SharePoint 2013).\r\nD. Incorrect: The auditing policy feature defines monitoring of user document interactions, \r\nsuch as edits, deletions, and so on.",
    "d_answer": " Incorrect: The auditing policy feature defines monitoring of user document interactions, \r\nsuch as edits, deletions, and so on.\r\n\r\n"
}, {
    "id": 0,
    "question": "3. Within the managed metadata service, you want to designate a set of terms specifically \r\nfor SharePoint navigation. What selection should you make within the Intended Use \r\ntab to accomplish this action?",
    "answer": ["D"],
    "a": "A. Use This Term Set For Managed Navigation\r\n",
    "b": "B. Make Term Set Unavailable For Tagging\r\n",
    "c": "C. Enable Team Site Navigation\r\n",
    "d": "D. Use This Term Set For Site Navigation\r\n\r",
    "a_answer": " Incorrect: Although managed navigation is the goal you are working toward, \r\nthere is no menu item by this name within the Intended Use tab.",
    "b_answer": " Incorrect: Making a term set unavailable for tagging is an effective way to group \r\nterms together (for example, by an alphabetical grouping, such as A�F), but does \r\nnot enable the term set for navigation.\r",
    "c_answer": " Incorrect: There is no option by this name in the Intended Use tab.\r\nD. Correct: The correct selection to enable managed navigation, it designates that a \r\nparticular term set be used explicitly for the navigation of a site (or sites).\r\n\r\n\r\n\r\n\r\n\r\nObjective 1.2: Thought experiment\r\n\r\nIn order to effectively maintain separation of content, you would most likely need to build a \r\nweb application that uses separate security credentials and content databases.",
    "d_answer": " Correct: The correct selection to enable managed navigation, it designates that a \r\nparticular term set be used explicitly for the navigation of a site (or sites).\r\n\r\n\r\n\r\n\r\n\r\nObjective 1.2: Thought experiment\r\n\r\nIn order to effectively maintain separation of content, you would most likely need to build a \r\nweb application that uses separate security credentials and content databases. Although this \r\nrequirement might not by itself preclude the use of host named site collections, the lack of \r\n"
}, {
    "id": 0,
    "question": "1. You are attempting to add new keywords to a SharePoint and receive a message that \r\nstates The Site Does Not Contain A Default Keywords Store. How should you correct \r\nthis issue?",
    "answer": ["B"],
    "a": "A. Add an enterprise keywords site column to the site’s content types.\r\n",
    "b": "B. In Central Administration, add an MMS application to the SharePoint farm.\r\n",
    "c": "C. Edit the MMS Connection and then select This Service Application Is The Default \r\nStorage Location For Keywords.\r\n",
    "d": "D. Activate the managed keyword service application in Central Administration.\r\n\r",
    "a_answer": " Incorrect: Although host named site collections technically use FQDNs in DNS, \r\nthis is not the correct designation for the site collection.",
    "b_answer": " Correct: Host named site collections allow for the assignment of vanity URLs to \r\neach site collection in a web application.\r",
    "c_answer": " Incorrect: There is no such thing as a domain named site collection.\r\nD. Incorrect: Path-based site collections are the alternative to host named site \r\ncollections.",
    "d_answer": " Incorrect: Path-based site collections are the alternative to host named site \r\ncollections.\r\n\r\n"
}, {
    "id": 0,
    "question": "2. You want to define a new information policy feature. The legal requirement for the \r\ndocument type requires that you produce and retain physical copies of each document. \r\nYou want to use a policy feature that will be supported in the next version of \r\nSharePoint.\r\n\r\n\r\nWhich of the following policy feature types should you choose?",
    "answer": ["B"],
    "a": "A. Retention\r\n",
    "b": "B. Bar codes\r\n",
    "c": "C. Labels\r\n",
    "d": "D. Auditing\r\n\r",
    "a_answer": " Incorrect: SharePoint is not aware of content databases replicated via log \r\nshipping.",
    "b_answer": " Correct: Each content database in SharePoint can specify an alternative SQL server \r\nfor use with mirroring.\r",
    "c_answer": " Incorrect: SharePoint is not aware of SQL availability groups.\r\nD. Incorrect: SharePoint is not aware of clustered SQL database servers.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n3. Correct answers: B, D\r\nA.",
    "d_answer": " Incorrect: SharePoint is not aware of clustered SQL database servers.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n3. Correct answers: B, D\r\nA. Incorrect: The limit of 20 web applications per SharePoint farm is a supported \r\nlimit.\r\nB. Correct: There is a supported limit of 20 web applications per SharePoint farm.\r\nC. Incorrect: The limit of 10 application pools per web server in a SharePoint farm is \r\n"
}, {
    "id": 0,
    "question": "3. Within the managed metadata service, you want to designate a set of terms specifically \r\nfor SharePoint navigation. What selection should you make within the Intended Use \r\ntab to accomplish this action?",
    "answer": ["B", "D"],
    "a": "A. Use This Term Set For Managed Navigation\r\n",
    "b": "B. Make Term Set Unavailable For Tagging\r\n",
    "c": "C. Enable Team Site Navigation\r\n",
    "d": "D. Use This Term Set For Site Navigation\r\n\r",
    "a_answer": " Incorrect: Content databases are not supported on NAS storage.",
    "b_answer": " Correct: RBS is fully supported on NAS storage.\r",
    "c_answer": " Incorrect: Configuration databases are not supported on NAS storage.\r\nD. Incorrect: Service application databases are not supported on NAS storage.\r\n\r\n\r\n\r\n2. Correct answer: C\r\nA.",
    "d_answer": " Incorrect: Service application databases are not supported on NAS storage.\r\n\r\n\r\n\r\n2. Correct answer: C\r\nA. Incorrect: There is no such mode in Request Management. Affinity has to do with \r\nserver load balancing on the web tier.\r\nB. Incorrect: An integrated mode server farm handles request management policies \r\n"
}, {
    "id": 0,
    "question": "1. You want to build a navigational structure in which each site collection can have \r\nits own vanity URL. Which site collection designation should be used for the web \r\napplication?",
    "answer": ["B"],
    "a": "A. Fully qualified domain name (FQDN) site collections\r\n",
    "b": "B. Host named site collections\r\n",
    "c": "C. Domain named site collections\r\n",
    "d": "D. Path-based site collections\r\n\r",
    "a_answer": " Incorrect: There is no such mode in Request Management.",
    "b_answer": " Incorrect: An integrated mode server farm handles request management policies \r",
    "c_answer": " Incorrect: Five servers would allow for load balancing in two of the three tiers.\r\nD.",
    "d_answer": " Correct: A six-server farm is the smallest practical design for load balancing in \r\neach tier.\r\n\r"
}, {
    "id": 0,
    "question": "2. Which of the following SQL high availability (HA) solutions require configuration in \r\nSharePoint content databases?",
    "answer": ["C"],
    "a": "A. SQL log shipping\r\n",
    "b": "B. SQL mirroring\r\n",
    "c": "C. SQL high availability groups\r\n",
    "d": "D. SQL clustering\r\n\r",
    "a_answer": " Incorrect: Three servers (one in each tier) would not provide any fault tolerance.",
    "b_answer": " Incorrect: Four servers would enable load balancing in two of the three tiers. Although \r",
    "c_answer": " Incorrect: Apps controls the installation and configuration of applications installed \r\nfrom the Office App Store. \r\nD.",
    "d_answer": " Correct: Quotas are part of the configuration for site collections.\r\n\r\n"
}, {
    "id": 0,
    "question": "3. Which of the following statements are true concerning web applications and application \r\npools in a SharePoint environment?",
    "answer": ["D"],
    "a": "A. There is a threshold limit of 20 web applications per SharePoint farm.\r\n",
    "b": "B. There is a supported limit of 20 web applications per SharePoint farm.\r\n",
    "c": "C. There is a supported limit of 10 application pools per web server in a SharePoint \r\nfarm.\r\n",
    "d": "D. There is a threshold limit of 10 application pools per web server in a SharePoint \r\n",
    "a_answer": " Incorrect: Settings controls the general settings of your SharePoint Online \r\nsubscription.",
    "b_answer": " Incorrect: Search controls the configuration of search in your SharePoint Online \r\nsubscription.\r",
    "c_answer": " Incorrect: There is no such authentication type.\r\nD. Incorrect: FBA is claims-based.\r\n\r\n\r\n\r\n3. Correct answers: A, B, D\r\nA.",
    "d_answer": " Incorrect: FBA is claims-based.\r\n\r\n\r\n\r\n3. Correct answers: A, B, D\r\nA. Correct: This S2S configuration is supported.\r\nB. Correct: This S2S configuration is supported.\r\nC. Incorrect: You cannot use S2S to configure an OAuth relationship between SharePoint \r\n"
}, {
    "id": 0,
    "question": "1. You want to build a navigational structure in which each site collection can have \r\nits own vanity URL. Which site collection designation should be used for the web \r\napplication?",
    "answer": ["B", "D"],
    "a": "A. Fully qualified domain name (FQDN) site collections\r\n",
    "b": "B. Host named site collections\r\n",
    "c": "C. Domain named site collections\r\n",
    "d": "D. Path-based site collections\r\n\r",
    "a_answer": " Correct: Windows classic is not claims-based, and must be configured from within \r\nWindows PowerShell.",
    "b_answer": " Incorrect: NTLM authentication is claims-based.\r",
    "c_answer": " Incorrect: Anonymous authentication cannot be configured at the site collection \r\nlevel.\r\nD.",
    "d_answer": " Incorrect: Anonymous authentication cannot be configured at the site level.\r\n\r\n"
}, {
    "id": 0,
    "question": "2. Which of the following SQL high availability (HA) solutions require configuration in \r\nSharePoint content databases?",
    "answer": ["A", "C"],
    "a": "A. SQL log shipping\r\n",
    "b": "B. SQL mirroring\r\n",
    "c": "C. SQL high availability groups\r\n",
    "d": "D. SQL clustering\r\n\r",
    "a_answer": " Correct: Anonymous authentication is configured at the zone level only.",
    "b_answer": " Incorrect: Anonymous authentication cannot be configured at the web application \r\nlevel.\r",
    "c_answer": " Incorrect: If selected, a members group can be created as part of the provisioning \r\nprocess.\r\nD.",
    "d_answer": " Incorrect: If selected, an owners group can be created as part of the provisioning \r\nprocess.\r\n\r"
}, {
    "id": 0,
    "question": "3. Which of the following statements are true concerning web applications and application \r\npools in a SharePoint environment?",
    "answer": ["D"],
    "a": "A. There is a threshold limit of 20 web applications per SharePoint farm.\r\n",
    "b": "B. There is a supported limit of 20 web applications per SharePoint farm.\r\n",
    "c": "C. There is a supported limit of 10 application pools per web server in a SharePoint \r\nfarm.\r\n",
    "d": "D. There is a threshold limit of 10 application pools per web server in a SharePoint \r\n",
    "a_answer": " Incorrect: If selected, a visitors group can be created as part of the provisioning \r\nprocess.",
    "b_answer": " Correct: There is no such default group.\r",
    "c_answer": " Incorrect: There is no such cmdlet.\r\nD. Correct: People Picker is configured using STSADM.\r\n\r\n\r\n\r\n3. Correct answers: B, C\r\nA.",
    "d_answer": " Correct: People Picker is configured using STSADM.\r\n\r\n\r\n\r\n3. Correct answers: B, C\r\nA. Incorrect: You cannot allow anonymous access at the web application level.\r\nB. Correct: Anonymous access can be configured for the entire web site.\r\nC. Correct: Anonymous access can be configured for lists and libraries.\r\n"
}, {
    "id": 0,
    "question": "1. You want to utilize NAS storage within your SharePoint farm. Which of the following \r\ncomponents are supported in this configuration?",
    "answer": ["C", "D"],
    "a": "A. Content databases\r\n",
    "b": "B. RBS\r\n",
    "c": "C. Configuration databases\r\n",
    "d": "D. Service application databases\r\n\r",
    "a_answer": " Incorrect: There is no such cmdlet.",
    "b_answer": " Incorrect: There is no such cmdlet.\r",
    "c_answer": " Incorrect: The Anonymous policy maintains its own set of permissions.\r\nD. Incorrect: There is no such web application policy.\r\n\r\n\r\n\r\n\r\n\r\nObjective 2.3: Thought experiment\r\n\r\nYou might begin by extending the web application that needs anonymous access using a different \r\nURL, which can be exposed through the firewall.",
    "d_answer": " Incorrect: There is no such web application policy.\r\n\r\n\r\n\r\n\r\n\r\nObjective 2.3: Thought experiment\r\n\r\nYou might begin by extending the web application that needs anonymous access using a different \r\nURL, which can be exposed through the firewall.\r\n\r\n"
}, {
    "id": 0,
    "question": "2. You want to build a server farm specifically intended to handle incoming request management \r\nprocessing duties. Which deployment mode should you choose?",
    "answer": ["A"],
    "a": "A. Affinity mode\r\n",
    "b": "B. Integrated mode\r\n",
    "c": "C. Dedicated mode\r\n",
    "d": "D. Throttling mode\r\n\r",
    "a_answer": " Correct: The Full Control, Full Read, Deny Write, and Deny All permission levels are \r\ncreated within this policy.",
    "b_answer": " Incorrect: The User policy associates individual users or groups with a permission \r\nlevel.\r",
    "c_answer": " Incorrect: There is no such feature.\r\nD. Incorrect: Only the Limited-Access User Permission Lockdown mode feature disallows \r\naccess.",
    "d_answer": " Incorrect: Only the Limited-Access User Permission Lockdown mode feature disallows \r\naccess.\r\n\r\n"
}, {
    "id": 0,
    "question": "3. The smallest fault-tolerant SharePoint 2013 farm should include how many servers?",
    "answer": ["A", "B", "D"],
    "a": "A. 3 (one in each tier)\r\n",
    "b": "B. 4\r\n",
    "c": "C. 5\r\n",
    "d": "D. 6\r\n\r",
    "a_answer": " Correct: If activated, this feature disallows access to the _layouts folder structure.",
    "b_answer": " Incorrect: There is no such feature.\r",
    "c_answer": " Incorrect: This tier should never be exposed to the Internet and should be behind \r\nthe DMZ and the back-end firewall.\r\nD.",
    "d_answer": " Correct: No SharePoint server should be exposed directly to the Internet without \r\nan active firewall.\r\n\r"
}, {
    "id": 0,
    "question": "1. You want to utilize NAS storage within your SharePoint farm. Which of the following \r\ncomponents are supported in this configuration?",
    "answer": ["A"],
    "a": "A. Content databases\r\n",
    "b": "B. RBS\r\n",
    "c": "C. Configuration databases\r\n",
    "d": "D. Service application databases\r\n\r",
    "a_answer": " Incorrect: The web tier servers should, at the very least, be placed behind a front-\r\nend, Internet-facing firewall.",
    "b_answer": " Incorrect: This tier should never be exposed to the Internet and should be behind \r\nthe DMZ and the back-end firewall.\r",
    "c_answer": " Incorrect: Partial answer.\r\nD. Correct: All three of these options are available.\r\n\r\n\r\n\r\n2. Correct answers: B, C\r\nA.",
    "d_answer": " Correct: All three of these options are available.\r\n\r\n\r\n\r\n2. Correct answers: B, C\r\nA. Incorrect: You cannot delegate administration at the zone level.\r\nB. Correct: You can delegate administration at the farm level.\r\nC. Correct: You can delegate administration at the farm level.\r\n"
}, {
    "id": 0,
    "question": "2. You want to build a server farm specifically intended to handle incoming request management \r\nprocessing duties. Which deployment mode should you choose?",
    "answer": ["B"],
    "a": "A. Affinity mode\r\n",
    "b": "B. Integrated mode\r\n",
    "c": "C. Dedicated mode\r\n",
    "d": "D. Throttling mode\r\n\r",
    "a_answer": " Incorrect: Partial answer.",
    "b_answer": " Incorrect: Partial answer.\r",
    "c_answer": " Incorrect: Partial answer.\r\nD. Correct: All three of these statements are true.\r\n\r\n\r\n\r\n4. Correct answer: C\r\nA.",
    "d_answer": " Correct: All three of these statements are true.\r\n\r\n\r\n\r\n4. Correct answer: C\r\nA. Incorrect: Settings for Web Part connections do not have anything to do with the \r\nuse of JavaScript in web parts.\r\nB. Incorrect: Settings for the Online Web Part Gallery do not have anything to do \r\n"
}, {
    "id": 0,
    "question": "3. The smallest fault-tolerant SharePoint 2013 farm should include how many servers?",
    "answer": ["D"],
    "a": "A. 3 (one in each tier)\r\n",
    "b": "B. 4\r\n",
    "c": "C. 5\r\n",
    "d": "D. 6\r\n\r",
    "a_answer": " Incorrect: Partial answer.",
    "b_answer": " Incorrect: Partial answer.\r",
    "c_answer": " Incorrect: Although you could count the number of cores and manually specify \r\nthat number as the max degree of parallelism, it would not be the correct value for \r\nuse with SharePoint.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n292 CHAPTER 3 Install and configure SharePoint farms\r\n\r\nD. Incorrect: This setting has nothing to do with the amount of RAM available to a \r\nsystem.",
    "d_answer": " Incorrect: This setting has nothing to do with the amount of RAM available to a \r\nsystem. Although you could count the number of cores and manually specify that \r\nnumber as the max degree of parallelism, it would not be the correct value for use \r\n"
}, {
    "id": 0,
    "question": "1. Which of the following Office 365 subscriptions include SharePoint Online as a component?",
    "answer": ["B", "C"],
    "a": "A. Office 365 Home Premium\r\n",
    "b": "B. Office 365 Small Business Premium\r\n",
    "c": "C. Office 365 ProPlus\r\n",
    "d": "D. Office 365 Enterprise\r\n\r",
    "a_answer": " Incorrect: Settings for Web Part connections do not have anything to do with the \r\nuse of JavaScript in web parts.",
    "b_answer": " Incorrect: Settings for the Online Web Part Gallery do not have anything to do \r\nwith the use of JavaScript in web parts.\r",
    "c_answer": " Incorrect: There is no such command.\r\nD.",
    "d_answer": " Correct: Regardless of the language wanted, all language packs install using the \r\nSharePoint Languagepack.exe command. From that point on, all dialogue is in the \r\n"
}, {
    "id": 0,
    "question": "2. Which of the following services are not included in SharePoint Online?",
    "answer": ["A"],
    "a": "A. Word Automation Services\r\n",
    "b": "B. Excel Calculation Services\r\n",
    "c": "C. PerformancePoint Services\r\n",
    "d": "D. Visio Graphics Services\r\n\r",
    "a_answer": " Incorrect: Setting the max degree of parallelism to 0 causes SQL to use a portion \r\nof the available processors to run a single statement (up to 64 total, depending on \r\nthe edition of SQL server used).\r\nB.",
    "b_answer": " Correct: 1 is the proper setting for the max degree of parallelism for use with \r\nSharePoint and suppresses parallel plan generation in SQL.\r\nC. Incorrect: Although you could count the number of cores and manually specify \r",
    "c_answer": " Incorrect: There is no such cmdlet.\r\nD. Incorrect: There is no such cmdlet.\r\n\r\n\r\n\r\n\r\n\r\nObjective 3.2: Thought experiment\r\n\r\nSMTP would need to be configured in the SharePoint environment.",
    "d_answer": " Incorrect: There is no such cmdlet.\r\n\r\n\r\n\r\n\r\n\r\nObjective 3.2: Thought experiment\r\n\r\nSMTP would need to be configured in the SharePoint environment. Due to the sales team�s \r\nrequirements, the drop box e-mail could potentially receive a lot of spam and the occasional \r\n"
}, {
    "id": 0,
    "question": "3. Your Office 365 users complain that they cannot share the contents of their site \r\ncollections with outside partners. Which section of the SharePoint admin center is appropriate \r\nfor correcting this issue?",
    "answer": ["A"],
    "a": "A. Settings\r\n",
    "b": "B. Search\r\n",
    "c": "C. Apps\r\n",
    "d": "D. Site collections\r\n\r",
    "a_answer": " Incorrect: There is no such command.",
    "b_answer": " Incorrect: Prerequisiteinstaller.exe downloads and configures SharePoint \r",
    "c_answer": " Incorrect: There is no such incoming e-mail scenario in SharePoint.\r\nD. Correct: The Advanced scenario routes incoming e-mail first through Exchange \r\nbefore arriving at the SharePoint server.",
    "d_answer": " Correct: The Advanced scenario routes incoming e-mail first through Exchange \r\nbefore arriving at the SharePoint server. This configuration provides all the spam \r\nfiltering and antivirus benefits Exchange has to offer.\r\n\r"
}, {
    "id": 0,
    "question": "1. Which of the following Office 365 subscriptions include SharePoint Online as a component?",
    "answer": ["D"],
    "a": "A. Office 365 Home Premium\r\n",
    "b": "B. Office 365 Small Business Premium\r\n",
    "c": "C. Office 365 ProPlus\r\n",
    "d": "D. Office 365 Enterprise\r\n\r",
    "a_answer": " Incorrect: Active Users and Computers is used to administer the Active Directory \r\nstructure.",
    "b_answer": " Correct: ADSI Edit is used to build the SCP container in Active Directory.\r",
    "c_answer": " Incorrect: The Get-SPServiceApplicationProxy cmdlet is used to retrieve information \r\nabout a service applications proxy.\r\nD.",
    "d_answer": " Incorrect: The Add-SPServiceApplicationProxyGroupMember cmdlet is used to \r\nadd a new service application proxy to a proxy group.\r\n\r"
}, {
    "id": 0,
    "question": "2. Which of the following services are not included in SharePoint Online?",
    "answer": ["A", "D"],
    "a": "A. Word Automation Services\r\n",
    "b": "B. Excel Calculation Services\r\n",
    "c": "C. PerformancePoint Services\r\n",
    "d": "D. Visio Graphics Services\r\n\r",
    "a_answer": " Incorrect: Although a supported scenario, Basic provides no spam filtering or virus \r\nprotection because incoming e-mail is not routed through an Exchange server.",
    "b_answer": " Incorrect: There is no such incoming e-mail scenario in SharePoint.\r",
    "c_answer": " Incorrect: There is no such command.\r\nD.",
    "d_answer": " Correct: The Set-SPDesignerSettings cmdlet is used to administer SPD settings for \r\na given web app.\r\n\r"
}, {
    "id": 0,
    "question": "3. Your Office 365 users complain that they cannot share the contents of their site \r\ncollections with outside partners. Which section of the SharePoint admin center is appropriate \r\nfor correcting this issue?",
    "answer": ["B", "C", "D"],
    "a": "A. Settings\r\n",
    "b": "B. Search\r\n",
    "c": "C. Apps\r\n",
    "d": "D. Site collections\r\n\r",
    "a_answer": " Correct: This cmdlet is the correct one for use in creating a new proxy group.",
    "b_answer": " Incorrect: The Get-SPServiceApplicationProxyGroup cmdlet is used to retrieve a \r\nlisting of proxy groups.\r",
    "c_answer": " Correct: The New-SPWOPIBinding cmdlet established the relationship between \r\nthe SharePoint farm and the Office Web Apps instance. An easy way to remember \r\nthe order is that the SharePoint farm is always connecting to the Office Web Apps \r\nfarm.",
    "d_answer": " Incorrect: There is no such cmdlet.\r\n\r"
}, {
    "id": 0,
    "question": "1. Which of the following are considered integrated Windows authentication types?",
    "answer": ["D"],
    "a": "A. Basic authentication\r\n",
    "b": "B. Forms authentication\r\n",
    "c": "C. Kerberos authentication\r\n",
    "d": "D. NTLM authentication\r\n\r",
    "a_answer": " Incorrect: There is no such cmdlet.",
    "b_answer": " Incorrect: Prerequisiteinstaller.exe downloads and configures SharePoint \r",
    "c_answer": " Incorrect: The index cannot be cloned.\r\nD. Correct: Cloning the search topology enables its alteration; after it is configured, it \r\ncan become the active topology.",
    "d_answer": " Correct: Cloning the search topology enables its alteration; after it is configured, it \r\ncan become the active topology.\r\n\r\n"
}, {
    "id": 0,
    "question": "2. Which of the following authentication types are not claims-based?",
    "answer": ["B", "C"],
    "a": "A. Windows classic authentication\r\n",
    "b": "B. NTLM authentication\r\n",
    "c": "C. Site collection authentication\r\n",
    "d": "D. Forms authentication\r\n\r",
    "a_answer": " Incorrect: There is no such cmdlet.",
    "b_answer": " Incorrect: There is no such cmdlet.\r",
    "c_answer": " Incorrect: Running a full crawl every evening may be functional, but would not \r\nkeep the index as fresh as possible throughout the day.\r\nD.",
    "d_answer": " Incorrect: Decreasing the continuous crawl interval would result in an increase in \r\ntraffic going across the WAN, potentially causing an outage for this location.\r\n\r"
}, {
    "id": 0,
    "question": "3. Which of the following are supported configurations for S2S?",
    "answer": ["D"],
    "a": "A. SharePoint 2013 to Exchange 2013\r\n",
    "b": "B. SharePoint 2013 to Lync 2013\r\n",
    "c": "C. SharePoint 2013 to SQL Server 2012\r\n",
    "d": "D. SharePoint 2013 to SharePoint 2013\r\n\r",
    "a_answer": " Incorrect: The index cannot be mirrored.",
    "b_answer": " Incorrect: There is no way to back up the search topology.\r",
    "c_answer": " Incorrect: There is no such connection group OOB.\r\nD. Incorrect: There is no such connection group OOB.\r\n\r\n\r\n\r\n2. Correct answer: C\r\nA.",
    "d_answer": " Incorrect: There is no such connection group OOB.\r\n\r\n\r\n\r\n2. Correct answer: C\r\nA. Incorrect: The term �Uncustomized� does not describe the status of a published \r\ncontent type.\r\nB. Incorrect: The term �Customized� does not describe the status of a published \r\n"
}, {
    "id": 0,
    "question": "4. At which of the following levels can anonymous authentication be configured in SharePoint?",
    "answer": ["C"],
    "a": "A. Zone\r\n",
    "b": "B. Web application\r\n",
    "c": "C. Site collection\r\n",
    "d": "D. Site\r\n\r",
    "a_answer": " Incorrect: Disabling the crawls would result in the index becoming stale over time.",
    "b_answer": " Correct: Increasing the continuous crawl interval would ease the traffic traversing \r\nthe WAN to this content source.\r",
    "c_answer": " Incorrect: The term �Sealed� does not describe the status of a published content \r\ntype.\r\nD.",
    "d_answer": " Correct: The term �Unsealed� describes the status of a published content type.\r\n\r\n"
}, {
    "id": 0,
    "question": "1. Which of the following are considered integrated Windows authentication types?",
    "answer": ["B", "D"],
    "a": "A. Basic authentication\r\n",
    "b": "B. Forms authentication\r\n",
    "c": "C. Kerberos authentication\r\n",
    "d": "D. NTLM authentication\r\n\r",
    "a_answer": " Correct: The custom connection is used to assign service application connections \r\non a one-off basis.",
    "b_answer": " Incorrect: The default connection is used by default for all connections.\r",
    "c_answer": " Incorrect: TCP 3389 is used with RDP connections.\r\nD. Correct: TCP 389 is used with Active Directory connections.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n4. Correct answer: D\r\nA.",
    "d_answer": " Correct: TCP 389 is used with Active Directory connections.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n4. Correct answer: D\r\nA. Incorrect: This is only one of the items to check.\r\nB. Incorrect: This is only one of the items to check.\r\nC. Incorrect: This is only one of the items to check.\r\n"
}, {
    "id": 0,
    "question": "2. Which of the following authentication types are not claims-based?",
    "answer": ["B"],
    "a": "A. Windows classic authentication\r\n",
    "b": "B. NTLM authentication\r\n",
    "c": "C. Site collection authentication\r\n",
    "d": "D. Forms authentication\r\n\r",
    "a_answer": " Incorrect: The term �Uncustomized� does not describe the status of a published \r\ncontent type.",
    "b_answer": " Incorrect: The term �Customized� does not describe the status of a published \r\ncontent type.\r",
    "c_answer": " Incorrect: This value does not correspond to any of the effective limits.\r\nD. Correct: The supported limit is 20 managed paths per web application; although \r\nexceeding this limit is technically possible, it negatively affects performance.",
    "d_answer": " Correct: The supported limit is 20 managed paths per web application; although \r\nexceeding this limit is technically possible, it negatively affects performance.\r\n\r\n"
}, {
    "id": 0,
    "question": "3. Which of the following are supported configurations for S2S?",
    "answer": ["D"],
    "a": "A. SharePoint 2013 to Exchange 2013\r\n",
    "b": "B. SharePoint 2013 to Lync 2013\r\n",
    "c": "C. SharePoint 2013 to SQL Server 2012\r\n",
    "d": "D. SharePoint 2013 to SharePoint 2013\r\n\r",
    "a_answer": " Incorrect: The term �Uncustomized� does not describe the status of a published \r\ncontent type.",
    "b_answer": " Incorrect: The term �Customized� does not describe the status of a published \r\ncontent type.\r",
    "c_answer": " Correct: The default threshold for the list view lookup is eight fields.\r\nD. Incorrect: This value does not correspond to any of the effective limits.\r\n\r\n\r\n\r\n3. Correct answer: A\r\nA.",
    "d_answer": " Incorrect: This value does not correspond to any of the effective limits.\r\n\r\n\r\n\r\n3. Correct answer: A\r\nA. Correct: Anonymous authentication is required to see the logon page.\r\nB. Incorrect: Basic authentication provides no security.\r\nC. Incorrect: Kerberos is not for external use (no access to the Key Distribution \r\n"
}, {
    "id": 0,
    "question": "4. At which of the following levels can anonymous authentication be configured in SharePoint?",
    "answer": ["B"],
    "a": "A. Zone\r\n",
    "b": "B. Web application\r\n",
    "c": "C. Site collection\r\n",
    "d": "D. Site\r\n\r",
    "a_answer": " Incorrect: TCP 1433 is used with SQL Server default connections.",
    "b_answer": " Incorrect: TCP 80 is used with HTTP connections.\r",
    "c_answer": " Correct: -HostHeader is the correct switch used to create host header site \r\ncollections.\r\nD.",
    "d_answer": " Incorrect: -HNSC is not a valid switch.\r\n\r\n"
}, {
    "id": 0,
    "question": "1. Which of the following default groups is cannot be automatically set up during the \r\nprovisioning of new SharePoint sites?",
    "answer": ["D"],
    "a": "A. Visitors\r\n",
    "b": "B. Authors\r\n",
    "c": "C. Members\r\n",
    "d": "D. Owners\r\n\r",
    "a_answer": " Incorrect: This is only one of the items to check.",
    "b_answer": " Incorrect: This is only one of the items to check.\r",
    "c_answer": " Correct: New Site is the correct link.\r\nD. Incorrect: Self Service Site is not the correct link.\r\n\r\n\r\n\r\n3. Correct answer: A\r\nA.",
    "d_answer": " Incorrect: Self Service Site is not the correct link.\r\n\r\n\r\n\r\n3. Correct answer: A\r\nA. Correct: A closed site is still available to its members.\r\nB. Incorrect: There is no such site type.\r\nC. Incorrect: There is no such site type.\r\n"
}, {
    "id": 0,
    "question": "2. Which of the following Windows PowerShell cmdlets is used to configure People \r\nPicker?",
    "answer": ["A"],
    "a": "A. Set-PeoplePicker\r\n",
    "b": "B. Set-PickerWebControl\r\n",
    "c": "C. Get-PeoplePicker\r\n",
    "d": "D. None of the above\r\n\r",
    "a_answer": " Incorrect: This value does not correspond to any of the effective limits.",
    "b_answer": " Incorrect: This value does not correspond to any of the effective limits.\r",
    "c_answer": " Incorrect: Business Connectivity Services is not required for site access requests.\r\nD. Incorrect: User Profile Services is not required for site access requests.\r\n\r\n\r\n\r\n2. Correct answers: B, C\r\nA.",
    "d_answer": " Incorrect: User Profile Services is not required for site access requests.\r\n\r\n\r\n\r\n2. Correct answers: B, C\r\nA. Incorrect: Although you can enable authentication at the web application level, \r\nyou cannot provide authorization at this level.\r\nB. Correct: Sites and site collections can be secured for anonymous access.\r\nC. Correct: Individual lists and libraries can be secured for anonymous access.\r\n"
}, {
    "id": 0,
    "question": "3. At which levels can you choose to explicitly allow anonymous access (authorization)?",
    "answer": ["D"],
    "a": "A. Web application\r\n",
    "b": "B. Web site\r\n",
    "c": "C. Lists and libraries\r\n",
    "d": "D. Individual item\r\n\r",
    "a_answer": " Incorrect: This is the maximum list view threshold.",
    "b_answer": " Incorrect: This is the maximum list view threshold for administrators and auditors.\r",
    "c_answer": " Incorrect: Partial answer � OpenSearch is one of the available protocols.\r\nD. Correct: All three of these protocols can be used with a result source in a SharePoint \r\nfarm.",
    "d_answer": " Correct: All three of these protocols can be used with a result source in a SharePoint \r\nfarm.\r\n\r\n"
}, {
    "id": 0,
    "question": "4. Which of the following web application policies is responsible for setting up individual \r\npermission levels at the web app level?",
    "answer": ["C"],
    "a": "A. Permission Policy\r\n",
    "b": "B. User Policy\r\n",
    "c": "C. Anonymous Policy\r\n",
    "d": "D. Inheritance Policy\r\n\r",
    "a_answer": " Correct: Anonymous authentication is required to see the logon page.",
    "b_answer": " Incorrect: Basic authentication provides no security.\r",
    "c_answer": " Correct: The System folder houses the display folders for result types.\r\nD. Incorrect: This folder does not house the display templates.\r\n\r\n\r\n\r\n4. Correct answer: C\r\nA.",
    "d_answer": " Incorrect: This folder does not house the display templates.\r\n\r\n\r\n\r\n4. Correct answer: C\r\nA. Incorrect: Managed properties is an available option.\r\nB. Incorrect: Categories is an available option.\r\nC. Correct: Filters are not an available option for configuration within the search \r\n"
}, {
    "id": 0,
    "question": "1. Which of the following default groups is cannot be automatically set up during the \r\nprovisioning of new SharePoint sites?",
    "answer": ["D"],
    "a": "A. Visitors\r\n",
    "b": "B. Authors\r\n",
    "c": "C. Members\r\n",
    "d": "D. Owners\r\n\r",
    "a_answer": " Incorrect: -HostNamed is not a valid switch.",
    "b_answer": " Incorrect: -HostHeaderSite is not a valid switch.\r",
    "c_answer": " Correct: The Intended Use tab allows for the configuration of term sets for navigational \r\nuse.\r\nD.",
    "d_answer": " Incorrect: The Custom Properties tab cannot be used to configure term sets for \r\nnavigational use.\r\n\r"
}, {
    "id": 0,
    "question": "2. Which of the following Windows PowerShell cmdlets is used to configure People \r\nPicker?",
    "answer": ["A", "B"],
    "a": "A. Set-PeoplePicker\r\n",
    "b": "B. Set-PickerWebControl\r\n",
    "c": "C. Get-PeoplePicker\r\n",
    "d": "D. None of the above\r\n\r",
    "a_answer": " Incorrect: The link is contained within a My Site.",
    "b_answer": " Incorrect: Team Site is not the correct link.\r",
    "c_answer": " Correct: Valid scope.\r\nD. Incorrect: Only the Shared and Local properties scopes are valid for custom \r\nproperties.",
    "d_answer": " Incorrect: Only the Shared and Local properties scopes are valid for custom \r\nproperties.\r\n\r\n"
}, {
    "id": 0,
    "question": "3. At which levels can you choose to explicitly allow anonymous access (authorization)?",
    "answer": ["B", "C"],
    "a": "A. Web application\r\n",
    "b": "B. Web site\r\n",
    "c": "C. Lists and libraries\r\n",
    "d": "D. Individual item\r\n\r",
    "a_answer": " Correct: A closed site is still available to its members.",
    "b_answer": " Incorrect: There is no such site type.\r",
    "c_answer": " Incorrect: Each content database can be associated with only one web application.\r\nD. Incorrect: Each content database can be associated with only one web application.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\nAnswers CHAPTER 5 485\r\n\r\n3. Correct answer: D\r\nA.",
    "d_answer": " Incorrect: Each content database can be associated with only one web application.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\nAnswers CHAPTER 5 485\r\n\r\n3. Correct answer: D\r\nA. Incorrect: Get-SPSiteCollection is not a valid Windows PowerShell cmdlet for use \r\nwith SharePoint.\r\nB. Incorrect: Get-SPDatabase �webapplication is used to display the content databases \r\n"
}, {
    "id": 0,
    "question": "4. Which of the following web application policies is responsible for setting up individual \r\npermission levels at the web app level?",
    "answer": ["B"],
    "a": "A. Permission Policy\r\n",
    "b": "B. User Policy\r\n",
    "c": "C. Anonymous Policy\r\n",
    "d": "D. Inheritance Policy\r\n\r",
    "a_answer": " Incorrect: Inbound e-mail is not required for site access requests.",
    "b_answer": " Correct: Outbound e-mail is sent via the SharePoint system to the designated e-\r\nmail address for approval requests.\r",
    "c_answer": " Correct: RAID 5 provides good read performance, effective redundancy, and also \r\nprovides the best economy.\r\nD.",
    "d_answer": " Incorrect: RAID 10 offers good performance and redundancy, but does not provide \r\nthe best economy.\r\n\r"
}, {
    "id": 0,
    "question": "1. Which of the following features can be activated to disable anonymous access to the \r\n_layouts folder?",
    "answer": ["A"],
    "a": "A. Limited-Access User Permission Lockdown mode\r\n",
    "b": "B. Forms Table Lockdown mode\r\n",
    "c": "C. Layouts and Web Services Lockdown mode\r\n",
    "d": "D. None of the above\r\n\r",
    "a_answer": " Incorrect: Partial answer � SharePoint is one of the available protocols.",
    "b_answer": " Incorrect: Partial answer � Exchange is one of the available protocols.\r",
    "c_answer": " Correct: TempDB Files and transaction logs would make the best use of this storage \r\nfrom a performance perspective.\r\nD.",
    "d_answer": " Incorrect: Database data files would benefit from the performance gain, but \r\nwould not provide the best use from a performance perspective.\r\n\r"
}, {
    "id": 0,
    "question": "2. In an Internet-facing SharePoint farm, which of the following SharePoint Server tiers \r\ndoes not require protection by a firewall?",
    "answer": ["C"],
    "a": "A. Web tier\r\n",
    "b": "B. App tier\r\n",
    "c": "C. Data tier\r\n",
    "d": "D. None of the above\r\n\r",
    "a_answer": " Incorrect: This folder does not house the display templates.",
    "b_answer": " Incorrect: This folder does not house the display templates.\r",
    "c_answer": " Incorrect: SQLIOSim is used for simulating SQL IO patterns.\r\nD. Incorrect: IOMeter is an open source tool that is used to test performance capacity \r\nwith multiple I/O types at one time.",
    "d_answer": " Incorrect: IOMeter is an open source tool that is used to test performance capacity \r\nwith multiple I/O types at one time.\r\n\r\n"
}, {
    "id": 0,
    "question": "3. When can a document be scanned by a SharePoint-integrated antivirus solution?",
    "answer": ["D"],
    "a": "A. On upload\r\n",
    "b": "B. At the end of a workflow\r\n",
    "c": "C. During a workflow\r\n",
    "d": "D. On download\r\n\r",
    "a_answer": " Incorrect: Managed properties is an available option.",
    "b_answer": " Incorrect: Categories is an available option.\r",
    "c_answer": " Incorrect: Disabled indicates that no caching will take place.\r\nD. Correct: This cache profile is optimized for sites in which authoring, customization, \r\nand other write-intensive operations take place.",
    "d_answer": " Correct: This cache profile is optimized for sites in which authoring, customization, \r\nand other write-intensive operations take place.\r\n\r\n"
}, {
    "id": 0,
    "question": "4. Which of the following certificate types is part of establishing a trust between SharePoint \r\nfarms?",
    "answer": ["C", "D"],
    "a": "A. An STS certificate generated by the publishing farm\r\n",
    "b": "B. A root certificate generated from the consuming farm\r\n",
    "c": "C. An STS certificate generated from the consuming farm\r\n",
    "d": "D. A root certificate generated by the publishing farm\r\n\r",
    "a_answer": " Incorrect: The General tab cannot be used to configure term sets for navigational \r\nuse.",
    "b_answer": " Incorrect: The Term-Driven Pages tab cannot be used to configure term sets for \r\nnavigational use.\r",
    "c_answer": " Correct: Event logs are not generally part of gathering a performance baseline.\r\nD. Incorrect: Creating a PerfMon schedule is part of collecting a performance \r\nbaseline.",
    "d_answer": " Incorrect: Creating a PerfMon schedule is part of collecting a performance \r\nbaseline.\r\n\r\n"
}, {
    "id": 0,
    "question": "1. Which of the following features can be activated to disable anonymous access to the \r\n_layouts folder?",
    "answer": ["B", "C", "D"],
    "a": "A. Limited-Access User Permission Lockdown mode\r\n",
    "b": "B. Forms Table Lockdown mode\r\n",
    "c": "C. Layouts and Web Services Lockdown mode\r\n",
    "d": "D. None of the above\r\n\r",
    "a_answer": " Correct: Valid scope.",
    "b_answer": " Incorrect: The Indexed properties scope is not valid for custom properties.\r",
    "c_answer": " Correct: BCS provide for client-side tracing.\r\nD. Incorrect: InfoPath Services do not provide for client-side tracing.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n3. Correct answer: A\r\nA.",
    "d_answer": " Incorrect: InfoPath Services do not provide for client-side tracing.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n3. Correct answer: A\r\nA. Correct: SSMS interaction is supported only with the logging database.\r\nB. Incorrect: Direct interaction with the User Profile Sync database is not supported.\r\nC. Incorrect: Direct interaction with the Search database is not supported.\r\n"
}, {
    "id": 0,
    "question": "2. In an Internet-facing SharePoint farm, which of the following SharePoint Server tiers \r\ndoes not require protection by a firewall?",
    "answer": ["A", "C", "D"],
    "a": "A. Web tier\r\n",
    "b": "B. App tier\r\n",
    "c": "C. Data tier\r\n",
    "d": "D. None of the above\r\n\r",
    "a_answer": " Incorrect: A content database always belongs to a web application for it to be \r\nfunctional with SharePoint.",
    "b_answer": " Correct: A web application can host many content databases, but a content database \r\ncan been associated only with a single web application.\r",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. When can a document be scanned by a SharePoint-integrated antivirus solution?",
    "answer": ["D"],
    "a": "A. On upload\r\n",
    "b": "B. At the end of a workflow\r\n",
    "c": "C. During a workflow\r\n",
    "d": "D. On download\r\n\r",
    "a_answer": " Incorrect: Get-SPSiteCollection is not a valid Windows PowerShell cmdlet for use \r\nwith SharePoint.",
    "b_answer": " Incorrect: Get-SPDatabase �webapplication is used to display the content databases \r\nthat are associated with a particular web application.\r",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following certificate types is part of establishing a trust between SharePoint \r\nfarms?",
    "answer": ["D"],
    "a": "A. An STS certificate generated by the publishing farm\r\n",
    "b": "B. A root certificate generated from the consuming farm\r\n",
    "c": "C. An STS certificate generated from the consuming farm\r\n",
    "d": "D. A root certificate generated by the publishing farm\r\n\r",
    "a_answer": " Incorrect: RAID 0 has excellent performance, but provides absolutely no redundancy.",
    "b_answer": " Incorrect: RAID 1 offers good performance and redundancy, but does not provide \r\nthe best economy.\r",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following options is available for using an RMS server in a SharePoint \r\nfarm?",
    "answer": ["D"],
    "a": "A. Do Not Use IRM On This Server\r\n",
    "b": "B. Use The Default RMS Server Specified In Active Directory\r\n",
    "c": "C. Specify An Existing RMS Server\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": " Incorrect: Database transaction logs would not provide the best use, although \r\nperformance would improve.",
    "b_answer": " Incorrect: Search databases can make very good use of this storage, but would \r\nnot provide the best use from a performance perspective.\r",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. In a growing SharePoint farm, at what levels might you choose to delegate administration?",
    "answer": ["C"],
    "a": "A. Web application\r\n",
    "b": "B. Farm\r\n",
    "c": "C. Service application\r\n",
    "d": "D. Zone\r\n\r",
    "a_answer": " Incorrect: SQLIO is used for testing performance capacity, one I/O type at a time.",
    "b_answer": " Correct: SQLIOStress is an older performance tool that was replaced by SQLIOSim.\r",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following statements are true concerning managed accounts?",
    "answer": ["A"],
    "a": "A. A system-generated password can be automatically provisioned\r\n",
    "b": "B. An administrator can enter a new password\r\n",
    "c": "C. An existing password can be used\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": " Incorrect: This cache profile is optimized for a site in which users are authenticated, \r\nbut no authoring or web part changes take place.",
    "b_answer": " Incorrect: This cache profile is optimized for anonymous users who receive the \r\nsame content.\r",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following Web Part security settings has to do with the use of \r\nJavaScript in Web Parts?",
    "answer": ["B", "C"],
    "a": "A. Web Part Connections\r\n",
    "b": "B. Online Web Part Gallery\r\n",
    "c": "C. Scriptable Web Parts\r\n",
    "d": "D. None of the above\r\n\r",
    "a_answer": " Incorrect: Building a data collector set is part of collecting a performance \r\nbaseline.",
    "b_answer": " Incorrect: Choosing a log storage location is part of collecting a performance \r\nbaseline.\r",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following options is available for using an RMS server in a SharePoint \r\nfarm?",
    "answer": ["C"],
    "a": "A. Do Not Use IRM On This Server\r\n",
    "b": "B. Use The Default RMS Server Specified In Active Directory\r\n",
    "c": "C. Specify An Existing RMS Server\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": " Incorrect: User Profile Services do not provide for client-side tracing.",
    "b_answer": " Incorrect: Search Services do not provide for client-side tracing.\r",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. In a growing SharePoint farm, at what levels might you choose to delegate administration?",
    "answer": ["C"],
    "a": "A. Web application\r\n",
    "b": "B. Farm\r\n",
    "c": "C. Service application\r\n",
    "d": "D. Zone\r\n\r",
    "a_answer": " Correct: SSMS interaction is supported only with the logging database.",
    "b_answer": " Incorrect: Direct interaction with the User Profile Sync database is not supported.\r",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following statements are true concerning managed accounts?",
    "answer": ["A"],
    "a": "A. A system-generated password can be automatically provisioned\r\n",
    "b": "B. An administrator can enter a new password\r\n",
    "c": "C. An existing password can be used\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following Web Part security settings has to do with the use of \r\nJavaScript in Web Parts?",
    "answer": ["A", "C"],
    "a": "A. Web Part Connections\r\n",
    "b": "B. Online Web Part Gallery\r\n",
    "c": "C. Scriptable Web Parts\r\n",
    "d": "D. None of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following commands or cmdlets can used to install the Application Server \r\nRole and Web Server Role on a new server in preparation for a SharePoint installation?",
    "answer": ["B"],
    "a": "A. Get-SPPreReqInstaller\r\n",
    "b": "B. Prerequisiteinstaller.exe\r\n",
    "c": "C. Get-ServerRole\r\n",
    "d": "D. Add-WindowsFeature\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. What is the proper value in SQL for the max degree of parallelism setting to support a \r\nSharePoint installation?",
    "answer": ["B", "C"],
    "a": "A. 0\r\n",
    "b": "B. 1\r\n",
    "c": "C. Equal to the number of processor cores on the SQL Server\r\n",
    "d": "D. Total amount of RAM/number of processor cores on the SQL Server\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following commands can be run to install the Spanish version of the \r\nSharePoint language pack?",
    "answer": ["B", "C", "D"],
    "a": "A. Sharepointupdate.exe\r\n",
    "b": "B. Prerequisiteinstaller.exe\r\n",
    "c": "C. SPLanguagePack.exe\r\n",
    "d": "D. Sharepointlanguagepack.exe\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following tools are used by an Active Directory administrator to create \r\nthe container for the SCP?",
    "answer": ["A", "C"],
    "a": "A. Active Directory Users and Computers\r\n",
    "b": "B. ADSIEdit.exe\r\n",
    "c": "C. Get-ADContainer\r\n",
    "d": "D. Set-ADContainer\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following commands or cmdlets can used to install the Application Server \r\nRole and Web Server Role on a new server in preparation for a SharePoint installation?",
    "answer": ["D"],
    "a": "A. Get-SPPreReqInstaller\r\n",
    "b": "B. Prerequisiteinstaller.exe\r\n",
    "c": "C. Get-ServerRole\r\n",
    "d": "D. Add-WindowsFeature\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. What is the proper value in SQL for the max degree of parallelism setting to support a \r\nSharePoint installation?",
    "answer": ["B", "C"],
    "a": "A. 0\r\n",
    "b": "B. 1\r\n",
    "c": "C. Equal to the number of processor cores on the SQL Server\r\n",
    "d": "D. Total amount of RAM/number of processor cores on the SQL Server\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following commands can be run to install the Spanish version of the \r\nSharePoint language pack?",
    "answer": ["C"],
    "a": "A. Sharepointupdate.exe\r\n",
    "b": "B. Prerequisiteinstaller.exe\r\n",
    "c": "C. SPLanguagePack.exe\r\n",
    "d": "D. Sharepointlanguagepack.exe\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following tools are used by an Active Directory administrator to create \r\nthe container for the SCP?",
    "answer": ["C"],
    "a": "A. Active Directory Users and Computers\r\n",
    "b": "B. ADSIEdit.exe\r\n",
    "c": "C. Get-ADContainer\r\n",
    "d": "D. Set-ADContainer\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following e-mail scenarios support the prevention of spam filtering and \r\nvirus prevention through incoming e-mail connectivity to a list or library in SharePoint?",
    "answer": ["C"],
    "a": "A. Basic scenario\r\n",
    "b": "B. List scenario\r\n",
    "c": "C. Library scenario\r\n",
    "d": "D. Advanced scenario\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following cmdlets is used to create a new proxy group for use with service \r\napplications?",
    "answer": ["A", "C"],
    "a": "A. Set-SPServiceApplicationProxyGroup\r\n",
    "b": "B. Get-SPServiceApplicationProxyGroup\r\n",
    "c": "C. Get-SPServiceApplicationProxy\r\n",
    "d": "D. Add-SPServiceApplicationProxyGroupMember\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following is the correct cmdlet to configure SPD settings within a web \r\napp?",
    "answer": ["A", "D"],
    "a": "A. Set-SharePointDesigner\r\n",
    "b": "B. Set-SPDesigner\r\n",
    "c": "C. Set-SharePointDesignerSettings\r\n",
    "d": "D. Set-SPDesignerSettings\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following cmdlets is used to bind an Office Web Apps installation with a \r\nSharePoint farm?",
    "answer": ["C"],
    "a": "A. Set-NewWOPIBinding\r\n",
    "b": "B. Set-NewSPBinding\r\n",
    "c": "C. New-SPWOPIBinding\r\n",
    "d": "D. New-WOPISPBinding\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following e-mail scenarios support the prevention of spam filtering and \r\nvirus prevention through incoming e-mail connectivity to a list or library in SharePoint?",
    "answer": ["A", "B", "D"],
    "a": "A. Basic scenario\r\n",
    "b": "B. List scenario\r\n",
    "c": "C. Library scenario\r\n",
    "d": "D. Advanced scenario\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following cmdlets is used to create a new proxy group for use with service \r\napplications?",
    "answer": ["B"],
    "a": "A. Set-SPServiceApplicationProxyGroup\r\n",
    "b": "B. Get-SPServiceApplicationProxyGroup\r\n",
    "c": "C. Get-SPServiceApplicationProxy\r\n",
    "d": "D. Add-SPServiceApplicationProxyGroupMember\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following is the correct cmdlet to configure SPD settings within a web \r\napp?",
    "answer": ["D"],
    "a": "A. Set-SharePointDesigner\r\n",
    "b": "B. Set-SPDesigner\r\n",
    "c": "C. Set-SharePointDesignerSettings\r\n",
    "d": "D. Set-SPDesignerSettings\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following cmdlets is used to bind an Office Web Apps installation with a \r\nSharePoint farm?",
    "answer": ["C"],
    "a": "A. Set-NewWOPIBinding\r\n",
    "b": "B. Set-NewSPBinding\r\n",
    "c": "C. New-SPWOPIBinding\r\n",
    "d": "D. New-WOPISPBinding\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. You want to modify the search topology of your farm. The body of content is quite \r\nlarge and has generated a large index. Which of the following is a required action for \r\nthis change?",
    "answer": ["C"],
    "a": "A. Mirroring the index\r\n",
    "b": "B. Backing up the topology\r\n",
    "c": "C. Cloning the index\r\n",
    "d": "D. Cloning the topology\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following content sources require additional configuration but are \r\ndirectly supported in a standard SharePoint Server 2013 search installation?",
    "answer": ["B"],
    "a": "A. Lotus Notes\r\n",
    "b": "B. Documentum\r\n",
    "c": "C. PeopleSoft\r\n",
    "d": "D. SAP\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following crawl types cannot be configured on the same content \r\nsource?",
    "answer": ["D"],
    "a": "A. Differential\r\n",
    "b": "B. Incremental\r\n",
    "c": "C. Continuous\r\n",
    "d": "D. Full\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. You receive a phone call from the remote site administrator of a small SharePoint \r\nserver farm whose content you have been crawling. The site has been experiencing \r\nconnectivity issues that occur only during working hours. Your requirement is that the \r\ncontent be kept as fresh as possible. What actions can you take to correct the issue?",
    "answer": ["C"],
    "a": "A. Disable all crawls\r\n",
    "b": "B. Increase the continuous crawl interval\r\n",
    "c": "C. Run a full crawl in the evening, but no other crawls\r\n",
    "d": "D. Decrease the continuous crawl interval\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. You want to modify the search topology of your farm. The body of content is quite \r\nlarge and has generated a large index. Which of the following is a required action for \r\nthis change?",
    "answer": ["C"],
    "a": "A. Mirroring the index\r\n",
    "b": "B. Backing up the topology\r\n",
    "c": "C. Cloning the index\r\n",
    "d": "D. Cloning the topology\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following content sources require additional configuration but are \r\ndirectly supported in a standard SharePoint Server 2013 search installation?",
    "answer": ["A"],
    "a": "A. Lotus Notes\r\n",
    "b": "B. Documentum\r\n",
    "c": "C. PeopleSoft\r\n",
    "d": "D. SAP\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following crawl types cannot be configured on the same content \r\nsource?",
    "answer": [null],
    "a": "A. Differential\r\n",
    "b": "B. Incremental\r\n",
    "c": "C. Continuous\r\n",
    "d": "D. Full\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. You receive a phone call from the remote site administrator of a small SharePoint \r\nserver farm whose content you have been crawling. The site has been experiencing \r\nconnectivity issues that occur only during working hours. Your requirement is that the \r\ncontent be kept as fresh as possible. What actions can you take to correct the issue?",
    "answer": [null],
    "a": "A. Disable all crawls\r\n",
    "b": "B. Increase the continuous crawl interval\r\n",
    "c": "C. Run a full crawl in the evening, but no other crawls\r\n",
    "d": "D. Decrease the continuous crawl interval\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following proxy/connection groups is used for one-off, ad hoc \r\nconnectivity?",
    "answer": [null],
    "a": "A. Custom\r\n",
    "b": "B. Default\r\n",
    "c": "C. Direct\r\n",
    "d": "D. Standby\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following terms describes the status of a content type that has been \r\npublished from the content type hub?",
    "answer": [null],
    "a": "A. Uncustomized\r\n",
    "b": "B. Customized\r\n",
    "c": "C. Sealed\r\n",
    "d": "D. Unsealed\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following terms describes the status of a content type that has been \r\nunpublished from the content type hub?",
    "answer": [null],
    "a": "A. Uncustomized\r\n",
    "b": "B. Customized\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n",
    "c": "C. Sealed\r\n",
    "d": "D. Unsealed\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following MMS Connection options should be enabled for web applications \r\nthat are already attached to another fully configured MMS Connection?",
    "answer": [null],
    "a": "A. This Service Application Is The Default Storage Location For Keywords\r\n",
    "b": "B. This Service Application Is The Default Storage Location For Column Specific Term \r\nSets\r\n",
    "c": "C. Consumes Content Types From The Content Type Gallery\r\n",
    "d": "D. Push-down Content Type Publishing Updates From The Content Type Gallery To \r\n",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following proxy/connection groups is used for one-off, ad hoc \r\nconnectivity?",
    "answer": [null],
    "a": "A. Custom\r\n",
    "b": "B. Default\r\n",
    "c": "C. Direct\r\n",
    "d": "D. Standby\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following terms describes the status of a content type that has been \r\npublished from the content type hub?",
    "answer": [null],
    "a": "A. Uncustomized\r\n",
    "b": "B. Customized\r\n",
    "c": "C. Sealed\r\n",
    "d": "D. Unsealed\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following terms describes the status of a content type that has been \r\nunpublished from the content type hub?",
    "answer": [null],
    "a": "A. Uncustomized\r\n",
    "b": "B. Customized\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n",
    "c": "C. Sealed\r\n",
    "d": "D. Unsealed\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following MMS Connection options should be enabled for web applications \r\nthat are already attached to another fully configured MMS Connection?",
    "answer": [null],
    "a": "A. This Service Application Is The Default Storage Location For Keywords\r\n",
    "b": "B. This Service Application Is The Default Storage Location For Column Specific Term \r\nSets\r\n",
    "c": "C. Consumes Content Types From The Content Type Gallery\r\n",
    "d": "D. Push-down Content Type Publishing Updates From The Content Type Gallery To \r\n",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following directory services are supported for use with SharePoint 2013?",
    "answer": [null],
    "a": "A. Active Directory Domain Services 2000\r\n",
    "b": "B. Sun Java System Directory Server 5.2\r\n",
    "c": "C. Novell eDirectory version 8.7.3\r\n",
    "d": "D. IBM Tivoli version 5.2\r\nE. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "5.2\r\nC. Novell eDirectory version 8.7.3\r\nD. IBM Tivoli version 5.2\r\nE. All of the above\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n2. Which of the following authentication types is supported for use with SharePoint Active \r\nDirectory import?",
    "answer": [null],
    "a": "A. Windows authentication\r\n",
    "b": "B. Basic authentication\r\n",
    "c": "C. Forms authentication\r\n",
    "d": "D. Trusted Claims Provider authentication\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which is the correct TCP port used with Active Directory imports?",
    "answer": [null],
    "a": "A. TCP 1433\r\n",
    "b": "B. TCP 80\r\n",
    "c": "C. TCP 3389\r\n",
    "d": "D. TCP 389\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. You have an audience that is working, but it displays stale or incomplete expected \r\nmembership information. Which of the following items should you check?",
    "answer": [null],
    "a": "A. Audience rules\r\n",
    "b": "B. Timer job for the synchronization service\r\n",
    "c": "C. Compilation schedule\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following directory services are supported for use with SharePoint 2013?",
    "answer": [null],
    "a": "A. Active Directory Domain Services 2000\r\n",
    "b": "B. Sun Java System Directory Server 5.2\r\n",
    "c": "C. Novell eDirectory version 8.7.3\r\n",
    "d": "D. IBM Tivoli version 5.2\r\nE. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "5.2\r\nC. Novell eDirectory version 8.7.3\r\nD. IBM Tivoli version 5.2\r\nE. All of the above\r\n\r\n\r\n\r\n\r\n\r\n\r\n\f\r\n2. Which of the following authentication types is supported for use with SharePoint Active \r\nDirectory import?",
    "answer": [null],
    "a": "A. Windows authentication\r\n",
    "b": "B. Basic authentication\r\n",
    "c": "C. Forms authentication\r\n",
    "d": "D. Trusted Claims Provider authentication\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which is the correct TCP port used with Active Directory imports?",
    "answer": [null],
    "a": "A. TCP 1433\r\n",
    "b": "B. TCP 80\r\n",
    "c": "C. TCP 3389\r\n",
    "d": "D. TCP 389\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. You have an audience that is working, but it displays stale or incomplete expected \r\nmembership information. Which of the following items should you check?",
    "answer": [null],
    "a": "A. Audience rules\r\n",
    "b": "B. Timer job for the synchronization service\r\n",
    "c": "C. Compilation schedule\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. What is the supported maximum number of managed paths for use in a SharePoint \r\nweb application?",
    "answer": [null],
    "a": "A. 5\r\n",
    "b": "B. 100\r\n",
    "c": "C. 35\r\n",
    "d": "D. 20\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following values is the default maximum List View Lookup Threshold?",
    "answer": [null],
    "a": "A. 5,000\r\n",
    "b": "B. 20,000\r\n",
    "c": "C. 8\r\n",
    "d": "D. 2,500\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following authentication methods is required for use with FBA?",
    "answer": [null],
    "a": "A. anonymous\r\n",
    "b": "B. basic\r\n",
    "c": "C. Kerberos\r\n",
    "d": "D. SAML\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following settings are required to enable a designer to build a new page \r\nlayout using SPD?",
    "answer": [null],
    "a": "A. Enable Detaching Pages From The Site Definition\r\n",
    "b": "B. Enable Customizing Master Pages And Layout Pages\r\n",
    "c": "C. Enable SharePoint Designer\r\n",
    "d": "D. Enable Managing Of The Web Site URL Structure\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. What is the supported maximum number of managed paths for use in a SharePoint \r\nweb application?",
    "answer": [null],
    "a": "A. 5\r\n",
    "b": "B. 100\r\n",
    "c": "C. 35\r\n",
    "d": "D. 20\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following values is the default maximum List View Lookup Threshold?",
    "answer": [null],
    "a": "A. 5,000\r\n",
    "b": "B. 20,000\r\n",
    "c": "C. 8\r\n",
    "d": "D. 2,500\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following authentication methods is required for use with FBA?",
    "answer": [null],
    "a": "A. anonymous\r\n",
    "b": "B. basic\r\n",
    "c": "C. Kerberos\r\n",
    "d": "D. SAML\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following settings are required to enable a designer to build a new page \r\nlayout using SPD?",
    "answer": [null],
    "a": "A. Enable Detaching Pages From The Site Definition\r\n",
    "b": "B. Enable Customizing Master Pages And Layout Pages\r\n",
    "c": "C. Enable SharePoint Designer\r\n",
    "d": "D. Enable Managing Of The Web Site URL Structure\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following switches is required for use in creating host header site collections \r\nin Windows PowerShell?",
    "answer": [null],
    "a": "A. -HostNamed\r\n",
    "b": "B. -HostHeaderSite\r\n",
    "c": "C. -HostHeader\r\n",
    "d": "D. -HNSC\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following links is used from My Site to create a new SSSC?",
    "answer": [null],
    "a": "A. My Site\r\n",
    "b": "B. Team Site\r\n",
    "c": "C. New Site\r\n",
    "d": "D. Self Service Site\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following terms describes a site that is no longer made available via aggregation \r\nbut is still available to its members?",
    "answer": [null],
    "a": "A. Closed\r\n",
    "b": "B. Offline\r\n",
    "c": "C. Unpublished\r\n",
    "d": "D. Dormant\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following Microsoft technologies is required for site mailboxes to be \r\nused?",
    "answer": [null],
    "a": "A. Microsoft Exchange\r\n",
    "b": "B. Office web applications\r\n",
    "c": "C. Outlook Web Access\r\n",
    "d": "D. Outgoing e-mail\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following switches is required for use in creating host header site collections \r\nin Windows PowerShell?",
    "answer": [null],
    "a": "A. -HostNamed\r\n",
    "b": "B. -HostHeaderSite\r\n",
    "c": "C. -HostHeader\r\n",
    "d": "D. -HNSC\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following links is used from My Site to create a new SSSC?",
    "answer": [null],
    "a": "A. My Site\r\n",
    "b": "B. Team Site\r\n",
    "c": "C. New Site\r\n",
    "d": "D. Self Service Site\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following terms describes a site that is no longer made available via aggregation \r\nbut is still available to its members?",
    "answer": [null],
    "a": "A. Closed\r\n",
    "b": "B. Offline\r\n",
    "c": "C. Unpublished\r\n",
    "d": "D. Dormant\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following Microsoft technologies is required for site mailboxes to be \r\nused?",
    "answer": [null],
    "a": "A. Microsoft Exchange\r\n",
    "b": "B. Office web applications\r\n",
    "c": "C. Outlook Web Access\r\n",
    "d": "D. Outgoing e-mail\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following services is required for use in configuring site access requests?",
    "answer": [null],
    "a": "A. Inbound email\r\n",
    "b": "B. Outbound email\r\n",
    "c": "C. Business Connectivity Services\r\n",
    "d": "D. User Profile Services\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following items can be individually secured for anonymous access?",
    "answer": [null],
    "a": "A. Web application\r\n",
    "b": "B. Site or site collection\r\n",
    "c": "C. Individual lists and libraries\r\n",
    "d": "D. Individual items\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. At which of the following levels can you configure security inheritance?",
    "answer": [null],
    "a": "A. Web application\r\n",
    "b": "B. Site or site collection\r\n",
    "c": "C. Individual lists and libraries\r\n",
    "d": "D. Individual items\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following permission groups cannot have its permissions altered?",
    "answer": [null],
    "a": "A. Full Control\r\n",
    "b": "B. Contribute\r\n",
    "c": "C. Limited Access\r\n",
    "d": "D. Read\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following services is required for use in configuring site access requests?",
    "answer": [null],
    "a": "A. Inbound email\r\n",
    "b": "B. Outbound email\r\n",
    "c": "C. Business Connectivity Services\r\n",
    "d": "D. User Profile Services\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following items can be individually secured for anonymous access?",
    "answer": [null],
    "a": "A. Web application\r\n",
    "b": "B. Site or site collection\r\n",
    "c": "C. Individual lists and libraries\r\n",
    "d": "D. Individual items\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. At which of the following levels can you configure security inheritance?",
    "answer": [null],
    "a": "A. Web application\r\n",
    "b": "B. Site or site collection\r\n",
    "c": "C. Individual lists and libraries\r\n",
    "d": "D. Individual items\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following permission groups cannot have its permissions altered?",
    "answer": [null],
    "a": "A. Full Control\r\n",
    "b": "B. Contribute\r\n",
    "c": "C. Limited Access\r\n",
    "d": "D. Read\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following protocols can be used within a result source?",
    "answer": [null],
    "a": "A. SharePoint\r\n",
    "b": "B. Exchange\r\n",
    "c": "C. OpenSearch\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. At which of the following levels can you configure query rules?",
    "answer": [null],
    "a": "A. Search service application\r\n",
    "b": "B. Site or site collection\r\n",
    "c": "C. Web application\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following folders houses the display templates for result types?",
    "answer": [null],
    "a": "A. Filters\r\n",
    "b": "B. Search\r\n",
    "c": "C. System\r\n",
    "d": "D. Content Web Parts\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following options is not available within the search service application for \r\nconfiguration?",
    "answer": [null],
    "a": "A. Managed properties\r\n",
    "b": "B. Categories\r\n",
    "c": "C. Filters\r\n",
    "d": "D. Crawled properties\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following protocols can be used within a result source?",
    "answer": [null],
    "a": "A. SharePoint\r\n",
    "b": "B. Exchange\r\n",
    "c": "C. OpenSearch\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. At which of the following levels can you configure query rules?",
    "answer": [null],
    "a": "A. Search service application\r\n",
    "b": "B. Site or site collection\r\n",
    "c": "C. Web application\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following folders houses the display templates for result types?",
    "answer": [null],
    "a": "A. Filters\r\n",
    "b": "B. Search\r\n",
    "c": "C. System\r\n",
    "d": "D. Content Web Parts\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following options is not available within the search service application for \r\nconfiguration?",
    "answer": [null],
    "a": "A. Managed properties\r\n",
    "b": "B. Categories\r\n",
    "c": "C. Filters\r\n",
    "d": "D. Crawled properties\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following tabs within the Term Set Management Tool is used to configure \r\na term set for navigation?",
    "answer": [null],
    "a": "A. General\r\n",
    "b": "B. Term-Driven Pages\r\n",
    "c": "C. Intended Use\r\n",
    "d": "D. Custom Properties\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following are valid scopes for custom properties?",
    "answer": [null],
    "a": "A. Shared properties\r\n",
    "b": "B. Indexed properties\r\n",
    "c": "C. Local properties\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. In which of the following can you configure a Search Refiner?",
    "answer": [null],
    "a": "A. Term store\r\n",
    "b": "B. Navigation tab\r\n",
    "c": "C. Custom properties\r\n",
    "d": "D. Web part\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. At which of the following levels can list refiners be configured?",
    "answer": [null],
    "a": "A. Site level\r\n",
    "b": "B. Site collection level\r\n",
    "c": "C. List or library level\r\n",
    "d": "D. Term Store level\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following tabs within the Term Set Management Tool is used to configure \r\na term set for navigation?",
    "answer": [null],
    "a": "A. General\r\n",
    "b": "B. Term-Driven Pages\r\n",
    "c": "C. Intended Use\r\n",
    "d": "D. Custom Properties\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following are valid scopes for custom properties?",
    "answer": [null],
    "a": "A. Shared properties\r\n",
    "b": "B. Indexed properties\r\n",
    "c": "C. Local properties\r\n",
    "d": "D. All of the above\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. In which of the following can you configure a Search Refiner?",
    "answer": [null],
    "a": "A. Term store\r\n",
    "b": "B. Navigation tab\r\n",
    "c": "C. Custom properties\r\n",
    "d": "D. Web part\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. At which of the following levels can list refiners be configured?",
    "answer": [null],
    "a": "A. Site level\r\n",
    "b": "B. Site collection level\r\n",
    "c": "C. List or library level\r\n",
    "d": "D. Term Store level\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following can be configured within a data collector set?",
    "answer": [null],
    "a": "A. Performance counters\r\n",
    "b": "B. Event trace data\r\n",
    "c": "C. Service application databases\r\n",
    "d": "D. System configuration information\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. How many web applications can be associated with a single content database in SharePoint?",
    "answer": [null],
    "a": "A. 0\r\n",
    "b": "B. 1\r\n",
    "c": "C. 2000\r\n",
    "d": "D. 5000\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following should you use to monitor the size of a single site within a site \r\ncollection?",
    "answer": [null],
    "a": "A. $site=Get-SPSiteCollection\r\n",
    "b": "B. $site.usage\r\n",
    "c": "C. Get-SPDatabase -webapplication\r\n",
    "d": "D. $site=get-spsite –identity http://\u003curl\u003e\r\nE. $site.usage\r\nF. Site settings, site collection administration, storage metrics\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following can be configured within a data collector set?",
    "answer": [null],
    "a": "A. Performance counters\r\n",
    "b": "B. Event trace data\r\n",
    "c": "C. Service application databases\r\n",
    "d": "D. System configuration information\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. How many web applications can be associated with a single content database in SharePoint?",
    "answer": [null],
    "a": "A. 0\r\n",
    "b": "B. 1\r\n",
    "c": "C. 2000\r\n",
    "d": "D. 5000\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following should you use to monitor the size of a single site within a site \r\ncollection?",
    "answer": [null],
    "a": "A. $site=Get-SPSiteCollection\r\n",
    "b": "B. $site.usage\r\n",
    "c": "C. Get-SPDatabase -webapplication\r\n",
    "d": "D. $site=get-spsite –identity http://\u003curl\u003e\r\nE. $site.usage\r\nF. Site settings, site collection administration, storage metrics\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. You are building an Internet-facing publishing portal. Content will be infrequently \r\nadded to this portal, but the majority of activity will be read-heavy. Which storage \r\nlevel offers the most cost-efficiencies while also providing the best performance characteristics \r\nand a layer of redundancy?",
    "answer": [null],
    "a": "A. RAID 0\r\n",
    "b": "B. RAID 1\r\n",
    "c": "C. RAID 5\r\n",
    "d": "D. RAID 10\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. You have a limited amount of RAID 10 storage available due to expense. Because you \r\nare configuring the SQL data tier of the SharePoint farm, you must decide how best to \r\nutilize this fast storage. Which of the following database groupings makes the best use \r\nof RAID 10 storage?",
    "answer": [null],
    "a": "A. Database transaction log files\r\n",
    "b": "B. Search databases\r\n",
    "c": "C. TempDB files and transaction logs\r\n",
    "d": "D. Database data files\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following current tools cannot be used to estimate the capacity of a SQL \r\n2008/2012 storage subsystem?",
    "answer": [null],
    "a": "A. SQLIO\r\n",
    "b": "B. SQLIOStress\r\n",
    "c": "C. SQLIOSim\r\n",
    "d": "D. IOMeter\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following ASP.NET cache profiles should be used for a collaborative site?",
    "answer": [null],
    "a": "A. Extranet\r\n",
    "b": "B. Public Internet\r\n",
    "c": "C. Disabled\r\n",
    "d": "D. Intranet\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. You are building an Internet-facing publishing portal. Content will be infrequently \r\nadded to this portal, but the majority of activity will be read-heavy. Which storage \r\nlevel offers the most cost-efficiencies while also providing the best performance characteristics \r\nand a layer of redundancy?",
    "answer": [null],
    "a": "A. RAID 0\r\n",
    "b": "B. RAID 1\r\n",
    "c": "C. RAID 5\r\n",
    "d": "D. RAID 10\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. You have a limited amount of RAID 10 storage available due to expense. Because you \r\nare configuring the SQL data tier of the SharePoint farm, you must decide how best to \r\nutilize this fast storage. Which of the following database groupings makes the best use \r\nof RAID 10 storage?",
    "answer": [null],
    "a": "A. Database transaction log files\r\n",
    "b": "B. Search databases\r\n",
    "c": "C. TempDB files and transaction logs\r\n",
    "d": "D. Database data files\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. Which of the following current tools cannot be used to estimate the capacity of a SQL \r\n2008/2012 storage subsystem?",
    "answer": [null],
    "a": "A. SQLIO\r\n",
    "b": "B. SQLIOStress\r\n",
    "c": "C. SQLIOSim\r\n",
    "d": "D. IOMeter\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "4. Which of the following ASP.NET cache profiles should be used for a collaborative site?",
    "answer": [null],
    "a": "A. Extranet\r\n",
    "b": "B. Public Internet\r\n",
    "c": "C. Disabled\r\n",
    "d": "D. Intranet\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following actions are not steps of collecting a performance baseline?",
    "answer": [null],
    "a": "A. Building a data collector set\r\n",
    "b": "B. Choosing a log storage location\r\n",
    "c": "C. Checking the application event logs\r\n",
    "d": "D. Creating a PerfMon schedule\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following SharePoint services can benefit from client-side tracing?",
    "answer": [null],
    "a": "A. User Profile Services\r\n",
    "b": "B. Search Services\r\n",
    "c": "C. BCS\r\n",
    "d": "D. InfoPath Services\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. SSMS interaction with which of the following SharePoint databases is supported?",
    "answer": [null],
    "a": "A. Logging\r\n",
    "b": "B. User Profile Sync\r\n",
    "c": "C. Search\r\n",
    "d": "D. BDC\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "1. Which of the following actions are not steps of collecting a performance baseline?",
    "answer": [null],
    "a": "A. Building a data collector set\r\n",
    "b": "B. Choosing a log storage location\r\n",
    "c": "C. Checking the application event logs\r\n",
    "d": "D. Creating a PerfMon schedule\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "2. Which of the following SharePoint services can benefit from client-side tracing?",
    "answer": [null],
    "a": "A. User Profile Services\r\n",
    "b": "B. Search Services\r\n",
    "c": "C. BCS\r\n",
    "d": "D. InfoPath Services\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}, {
    "id": 0,
    "question": "3. SSMS interaction with which of the following SharePoint databases is supported?",
    "answer": [null],
    "a": "A. Logging\r\n",
    "b": "B. User Profile Sync\r\n",
    "c": "C. Search\r\n",
    "d": "D. BDC\r\n\r",
    "a_answer": "e",
    "b_answer": "f",
    "c_answer": "g",
    "d_answer": "h"
}];
